[tool.black]
line-length = 70
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/foo.py  # exclude a file named foo.py in the root of the project (in addition to the defaults)
'''

[tool.isort]
profile = "black"
atomic = true
group_by_package = true
py_version = 39
skip = [".gitignore", ".dockerignore"]
line_length = 70
sections = [
  'FUTURE',
  'STDLIB',
  'TORCH',
  'AVALANCHE',
  'DOIT',
  'THIRDPARTY',
  'FIRSTPARTY',
  'LOCALFOLDER',
]
known_torch = ['torch', 'pytorchcv']
known_avalanche = ['avalanche']
known_doit = ['doit']

[tool.mypy]
files = ["src", "workflow", "*.py"]
exclude = [
  '^wandb',
  '^tests',
  '^OLD_FILES',
  '^src/utils/summary.py',
]
plugins = [
  # "pydantic.mypy"
]
ignore_missing_imports = true
# follow_imports = "silent"
# warn_redundant_casts = true
# warn_unused_ignores = true
# disallow_any_generics = true
# check_untyped_defs = true
# no_implicit_reexport = true

# for strict mypy: (this is the tricky one :-))
# disallow_untyped_defs = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

[tool.pyright]
include = ["src", "workflow", "*.py"]
exclude = [
  "**/node_modules", 
  "**/__pycache__", 
  "**/.mypy_cache", 
  "**/.pytest_cache", 
  "**/.git", 
  "**/.vscode", 
  "**/OLD_FILES",
  "**/wandb",
  "**/.ipynb_checkpoints",
]
ignore = []
